# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 12a4de82b0bec7d92312c532099a3d1608bb4fb4f49f76096d99f6767eb3d57b4af8f9abd4a7958ad9941e63f76e4bd43b0120c388c4bb62c3c54905e32c753a

test:
  secret_key_base: 7b2d53f819686820aa6a7f29f9c07b1b2883bebd85a545e63e069fedbad51ab077300fdfca44f27122b5df69366b12e298b59002597a1a7a05e3f9e27647ec40

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
